INHERIT: ./template.yml

site_author: 'FFW Baudenbach'
site_description: 'Dokumentation der FFW Baudenbach'
site_dir: 'public'
site_name: 'Dokumentation'
site_url: 'https://ffw-baudenbach.github.io/FE2_Documentation/'

repo_name: 'FE2_Documentation'
repo_url: 'https://github.com/FFW-Baudenbach/FE2_Documentation'
edit_uri: 'edit/main/docs/'

plugins:
  - search
  - htmlproofer:
      raise_error: !ENV [ENABLE_LINK_CHECK, True] #Disabled locally to not break 'mkdoc serve' on every typo...
      validate_external_urls: False
  - git-revision-date-localized:
      enabled: !ENV [ENABLE_GIT_REVISION_DATE, False] #Disabled locally to speed up build time
      type: datetime
      timezone: Europe/Berlin
      enable_creation_date: true